package:
  name: tweeps
  version: 0.1.0

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
  home: https://github.com/CurtLH/tweeps
  summary: The tweeps application provides a simple way to connect to the the Twitter Streaming API. After you submit your keywords and hashtags to tweeps, the application will maintain a constant connection to the API, and store new tweets in a PostgreSQL database as they come into the system. The application also includes an ETL process that will regularily monitor the source database and routinely extract, transform, and load data from the source database into a data warehouse.
